[workspace]
resolver = "3"
members = [
    "crates/fhirpg-map",
    "crates/fhirpg-gen",
    "crates/fhirpg-store",
    "crates/fhirpg-server",
    "crates/fhirpg",
]

[workspace.package]
version = "0.3.1"
keywords = ["fhir", "healthcare", "postgresql", "hl7", "medical"]
categories = ["database", "science", "command-line-utilities"]
edition = "2024"
license = "MIT OR Apache-2.0 OR BSD-3-Clause OR GPL-2.0-only OR GPL-3.0-only"
repository = "https://github.com/fhirpg/fhirpg"
rust-version = "1.90"

[workspace.dependencies]
fhirpg-map = { path = "crates/fhirpg-map", version = "0.3.1" }
fhirpg-gen = { path = "crates/fhirpg-gen", version = "0.3.1" }
fhirpg-store = { path = "crates/fhirpg-store", version = "0.3.1" }
fhirpg-server = { path = "crates/fhirpg-server", version = "0.3.1" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision", "preserve_order"] }
thiserror = "2"
anyhow = "1"
flate2 = "1"
unicode-normalization = "0.1"
sha2 = "0.10"
sha3 = "0.10"
hmac = "0.12"
subtle = "2"
zeroize = { version = "1", features = ["zeroize_derive"] }
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync", "time"] }
tokio-postgres = "0.7"
deadpool-postgres = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = "thin"
