//! Fidelity of the transformation against fhirbase itself.
//!
//! Spec invariant 4: for the nine vendored FHIR versions, transform output MUST
//! be `serde_json::Value`-equal to fhirbase's for the same input. This is the
//! test that holds us to it, and it is the single strongest piece of evidence
//! that the port of `transform.go` is correct.
//!
//! # Where the expected output came from
//!
//! `tests/data/fidelity/expected/<version>/<case>.json` was **generated by
//! fhirbase's own Go code**, not written by hand. The generator extracted
//! `getByPath`, `transform`, `getTransformData`, and `doTransform` verbatim
//! from `~/github/fhirbase/fhirbase/transform.go` — the only edits were
//! replacing the `packr` asset lookup with a filesystem read and adding a
//! `main` that reads a file and prints the result — then ran every input
//! through it at each version.
//!
//! Regenerating requires a Go toolchain and a fhirbase checkout, so the outputs
//! are committed. That keeps this test running in CI, and on any machine,
//! without either.
//!
//! # Why comparison is on `Value`
//!
//! Object key order is not significant (spec invariant 4). Go's `map` iteration
//! is randomized, so fhirbase's byte output is not even stable run to run;
//! `serde_json::Value` equality is the meaningful comparison.
//!
//! # Coverage
//!
//! 34 resources across 4 versions — 136 comparisons. The corpus spans 15
//! resource types and deliberately includes the awkward edges: choice elements
//! of every shape, references that do and do not split, the lossy reference
//! rewrite, `tr/move` redirection, repeating and nested-array fields, unknown
//! resource types, unicode and escapes, empty arrays, and nulls.

// An integration test is a separate crate compiled as a normal binary, so the
// `cfg(test)` exemption in `src/main.rs` does not reach it, but the workspace's
// denied panic lints do. Panicking IS how a test reports, so exempt this crate.
#![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::process::Command;

/// The FHIR versions the corpus was generated for.
const VERSIONS: &[&str] = &["1.0.2", "3.0.1", "3.3.0", "4.0.0"];

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/fidelity")
}

/// Runs the real binary, as a user would, and returns its parsed stdout.
fn transform(version: &str, input: &Path) -> serde_json::Value {
    let output = Command::new(env!("CARGO_BIN_EXE_fhirpg"))
        .args(["--fhir", version, "transform"])
        .arg(input)
        .output()
        .unwrap_or_else(|e| panic!("cannot run fhirpg: {e}"));

    assert!(
        output.status.success(),
        "fhirpg --fhir {version} transform {} failed: {}",
        input.display(),
        String::from_utf8_lossy(&output.stderr)
    );

    serde_json::from_slice(&output.stdout).unwrap_or_else(|e| {
        panic!(
            "fhirpg emitted invalid JSON for {} at {version}: {e}",
            input.display()
        )
    })
}

fn read_json(path: &Path) -> serde_json::Value {
    let bytes =
        std::fs::read(path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

/// Every corpus input, sorted so failures are reported in a stable order.
fn corpus() -> Vec<PathBuf> {
    let input_dir = data_dir().join("input");
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&input_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", input_dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    paths.sort();
    assert!(
        paths.len() >= 20,
        "spec §4.8 requires a corpus of at least 20 resources, found {}",
        paths.len()
    );
    paths
}

#[test]
fn transform_matches_fhirbase_across_every_corpus_case() {
    let corpus = corpus();
    let mut compared = 0;
    let mut mismatches = Vec::new();

    for version in VERSIONS {
        for input in &corpus {
            let case = input
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("<unnamed>");

            let expected_path = data_dir().join("expected").join(version).join(case);
            let expected = read_json(&expected_path);
            let actual = transform(version, input);

            compared += 1;
            if actual != expected {
                mismatches.push(format!(
                    "\n--- {version} / {case} ---\nfhirbase: {}\nfhirpg:   {}",
                    serde_json::to_string(&expected).unwrap_or_default(),
                    serde_json::to_string(&actual).unwrap_or_default(),
                ));
            }
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} of {compared} comparisons diverge from fhirbase:{}",
        mismatches.len(),
        mismatches.join("")
    );

    assert_eq!(
        compared,
        corpus.len() * VERSIONS.len(),
        "every case must be compared at every version"
    );
}

#[test]
fn corpus_covers_a_range_of_resource_types() {
    // Spec §4.8 asks for at least five resource types; guard against the corpus
    // being quietly narrowed.
    let mut types = std::collections::BTreeSet::new();
    for input in corpus() {
        if let Some(t) = read_json(&input)
            .get("resourceType")
            .and_then(serde_json::Value::as_str)
        {
            types.insert(t.to_owned());
        }
    }
    assert!(
        types.len() >= 5,
        "corpus covers only {} resource types: {types:?}",
        types.len()
    );
}

#[test]
fn corpus_exercises_the_transformation_edges() {
    // A corpus that never triggers a rewrite would pass vacuously. Assert the
    // cases that matter are present and actually change under transformation.
    let checks: &[(&str, &str)] = &[
        ("patient_full.json", "deceased"),
        ("claim_union_ref.json", "value"),
        ("careplan.json", "careTeam"),
        ("unknown_type.json", "resourceType"),
        ("ref_lossy.json", "managingOrganization"),
    ];

    for (case, key) in checks {
        let path = data_dir().join("input").join(case);
        assert!(path.exists(), "corpus is missing {case}");
        let out = transform("4.0.0", &path);
        assert!(
            out.get(*key).is_some() || out.get("information").is_some(),
            "{case} should produce a {key} key, got {out}"
        );
    }

    // The lossy reference rewrite (spec §4.5) really is lossy.
    let lossy = transform("4.0.0", &data_dir().join("input/ref_lossy.json"));
    let org = &lossy["managingOrganization"];
    assert_eq!(org["id"], serde_json::json!("1"));
    assert_eq!(org["resourceType"], serde_json::json!("Organization"));
    assert!(org.get("identifier").is_none(), "identifier must be dropped");
    assert!(org.get("type").is_none(), "type must be dropped");
    assert!(org.get("extension").is_none(), "extension must be dropped");

    // An unknown resource type passes through untouched (spec §4.2 step 2).
    let unknown_in = read_json(&data_dir().join("input/unknown_type.json"));
    let unknown_out = transform("4.0.0", &data_dir().join("input/unknown_type.json"));
    assert_eq!(unknown_in, unknown_out);
}
