[book]
title = "fhirpg"
description = "Import FHIR data into PostgreSQL and work with it relationally."
authors = ["Joel Parker Henderson"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/joelparkerhenderson/fhirpg"
