//! The relational map: a compact, serializable description of how one FHIR
//! version's resources shred into relational tables. Generated by
//! `fhirpg-gen` from the official StructureDefinitions; consumed by the
//! generic shred/reconstruct engine and the DDL emitter.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// The complete relational map for one FHIR version.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelMap {
    /// FHIR publication version, e.g. "5.0.0".
    pub fhir_version: String,
    /// PostgreSQL schema name, e.g. "r5".
    pub schema: String,
    pub resources: BTreeMap<String, ResourceMap>,
}

/// One resource type's tables and element tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceMap {
    /// Resource type name, e.g. "Patient".
    pub name: String,
    /// Table 0 is the base table; the fixed-shape system tables (ext, deep,
    /// contained, history) are also in this list so DDL and stores can
    /// enumerate everything.
    pub tables: Vec<Table>,
    /// Node arena. Nodes reference each other by index, which permits the
    /// cycles that recursive elements (contentReference) require.
    pub nodes: Vec<Node>,
    /// Root node (the resource's own elements). Always present in practice;
    /// index into `nodes`.
    pub root: u32,
    /// Compiled search parameters, generated from the version's
    /// SearchParameter definitions.
    #[serde(default)]
    pub search: Vec<SearchDef>,
}

/// One search parameter, compiled against this resource's tables.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchDef {
    /// Parameter code as used in query strings ("family", "code", …).
    pub code: String,
    pub ty: SearchTy,
    /// Places this parameter matches; a value matches when ANY target does.
    /// Empty means the parameter is known but not yet compilable — servers
    /// report it unsupported instead of lying.
    pub targets: Vec<SearchTarget>,
    /// Why targets are empty, for the generated support matrix.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SearchTy {
    Number,
    Date,
    String,
    Token,
    Reference,
    Composite,
    Quantity,
    Uri,
    Special,
}

/// One concrete place a search parameter matches: a table plus the columns
/// the predicate tests.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchTarget {
    /// Index into `ResourceMap.tables`; 0 = base table (no join needed).
    pub table: u32,
    pub kind: TargetKind,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TargetKind {
    /// Case-insensitive prefix/contains match on a text column.
    Str {
        col: String,
    },
    /// system|code semantics. `system` is None for bare code/boolean
    /// primitives.
    Token {
        system: Option<String>,
        code: String,
    },
    /// Temporal comparison against the derived sort column; `hi` is the end
    /// column for Period elements.
    Date {
        lo: String,
        hi: Option<String>,
    },
    Number {
        col: String,
    },
    Quantity {
        value: String,
        system: Option<String>,
        code: Option<String>,
    },
    Reference {
        c_type: String,
        c_id: String,
        c_url: String,
    },
    Uri {
        col: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TableKind {
    /// One row per resource: `id text PRIMARY KEY, version_id bigint,
    /// last_updated timestamptz`, plus data columns.
    Base,
    /// One row per instance of a repeating (or force-split) element:
    /// `rid text, ords smallint[]`, PK (rid, ords), plus data columns.
    Elem,
    /// Extension leaves: `rid, path, ords, modifier, ext_ord, url, leaf,
    /// v_kind, v_text, v_num, v_bool`.
    Ext,
    /// Type-recursion spill leaves: `rid, path, ords, leaf, v_kind, v_text,
    /// v_num, v_bool`.
    Deep,
    /// Contained resources: `rid, ord, resource jsonb`.
    Contained,
    /// Version history: `id, version_id, last_updated, op, resource jsonb`.
    History,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Table {
    pub name: String,
    pub kind: TableKind,
    /// FHIR element path this table stores ("Patient.name.given");
    /// empty for base and system tables.
    pub path: String,
    /// Data columns. Empty for the fixed-shape system tables.
    pub cols: Vec<Column>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    pub ty: ColTy,
    /// FHIR element path this column stores, for documentation and search
    /// compilation ("Patient.birthDate", "Observation.value[x]:Quantity.value").
    pub path: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ColTy {
    Bool,
    Int,
    BigInt,
    Numeric,
    Text,
    /// Derived sort column for a FHIR date.
    Date,
    /// Derived sort column for a FHIR dateTime/instant.
    Timestamptz,
    Jsonb,
}

/// One object context: the elements of a resource root, backbone element, or
/// complex datatype, flattened into the current table row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    pub elems: Vec<Elem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Elem {
    /// JSON property name ("birthDate"; for a choice variant, the full name
    /// "valueBoolean"; for a choice element itself, the base name "value").
    pub json: String,
    /// FHIR element path, for error messages and documentation.
    pub path: String,
    /// True when max cardinality exceeds 1 (JSON array).
    pub repeats: bool,
    /// When Some, instances of this element get their own row in the given
    /// table (index into `ResourceMap.tables`): every repeating element, and
    /// non-repeating elements force-split to respect PostgreSQL's column
    /// limit. The row's `ords` is the parent's ords plus the 1-based array
    /// index (or 1 when the element does not repeat).
    pub table: Option<u32>,
    /// Lane sign for cyclic contentReference elements. When two elements
    /// recurse into the same table (QuestionnaireResponse: `item.item` and
    /// `item.answer.item` both target #QuestionnaireResponse.item), their
    /// ordinal paths would collide; the second referrer pushes negated
    /// ordinals so every path stays unambiguous.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub neg_lane: bool,
    pub kind: ElemKind,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ElemKind {
    Prim(PrimCol),
    /// The `Reference.reference` string, split into parsed columns.
    RefStr(RefCols),
    /// Complex datatype or backbone element: node index into the arena.
    /// Cyclic contentReference elements point back at an ancestor node and
    /// share its table.
    Group(u32),
    /// Choice element; each variant is a complete Elem whose `json` is the
    /// full variant property name.
    Choice(Vec<Elem>),
    /// Type-recursion cut: the whole subtree spills to the Deep table as
    /// leaf rows.
    Spill,
    /// An inline resource (e.g. Bundle.entry.resource) stored whole in a
    /// jsonb column.
    ResourceValue(String),
    /// DomainResource.contained, stored in the Contained table.
    Contained,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrimCol {
    pub col: String,
    /// Derived sort column for temporal primitives.
    pub sort: Option<String>,
    pub prim: Prim,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefCols {
    /// Column holding the target resource type of a relative reference.
    pub c_type: String,
    /// Column holding the target id of a relative reference.
    pub c_id: String,
    /// Column holding any other reference verbatim (absolute URL, urn:,
    /// fragment, version-specific).
    pub c_url: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Prim {
    /// JSON bool → boolean.
    Bool,
    /// integer/unsignedInt/positiveInt: JSON number → integer.
    Int,
    /// R5 integer64: JSON string → bigint.
    Int64,
    /// JSON number → numeric, lexical form preserved.
    Decimal,
    /// JSON string, possibly partial ("2026-07") → text + date sort.
    Date,
    /// JSON string → text + timestamptz sort.
    DateTime,
    /// JSON string, always fully specified → text + timestamptz sort.
    Instant,
    /// JSON string → text (kept lexical for fractional-second fidelity).
    Time,
    /// Everything else stringly: string/code/id/uri/url/canonical/oid/uuid/
    /// markdown/xhtml/base64Binary → text.
    Str,
}

impl Prim {
    pub fn col_ty(self) -> ColTy {
        match self {
            Prim::Bool => ColTy::Bool,
            Prim::Int => ColTy::Int,
            Prim::Int64 => ColTy::BigInt,
            Prim::Decimal => ColTy::Numeric,
            Prim::Date | Prim::DateTime | Prim::Instant | Prim::Time | Prim::Str => ColTy::Text,
        }
    }

    pub fn sort_ty(self) -> Option<ColTy> {
        match self {
            Prim::Date => Some(ColTy::Date),
            Prim::DateTime | Prim::Instant => Some(ColTy::Timestamptz),
            _ => None,
        }
    }
}

impl RelMap {
    pub fn to_gz_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        use flate2::{Compression, write::GzEncoder};
        use std::io::Write as _;
        let json = serde_json::to_vec(self)?;
        let mut enc = GzEncoder::new(Vec::new(), Compression::default());
        enc.write_all(&json).expect("gz write");
        Ok(enc.finish().expect("gz finish"))
    }

    pub fn from_gz_bytes(bytes: &[u8]) -> Result<Self, std::io::Error> {
        use flate2::read::GzDecoder;
        let dec = GzDecoder::new(bytes);
        serde_json::from_reader(dec).map_err(std::io::Error::other)
    }
}

impl ResourceMap {
    pub fn node(&self, id: u32) -> &Node {
        &self.nodes[id as usize]
    }

    pub fn table(&self, id: u32) -> &Table {
        &self.tables[id as usize]
    }

    pub fn base_table(&self) -> &Table {
        &self.tables[0]
    }

    pub fn find_table(&self, kind: TableKind) -> Option<(u32, &Table)> {
        self.tables
            .iter()
            .enumerate()
            .find(|(_, t)| t.kind == kind)
            .map(|(i, t)| (i as u32, t))
    }
}
